apiVersion: apps/v1
kind: Deployment
metadata:
    name: matching
    labels:
        app: matching
spec:
    replicas: 1
    selector:
        matchLabels:
            app: matching
    template:
        metadata:
            labels:
                app: matching
        spec:
            containers:
                - name: matching
                  image: lavorocontainers.azurecr.io/matching:<tag>
                  ports:
                      - containerPort: 80
                  env:
                      - name: AMQP_URL
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq-url
                                key: AMQP_URL
                      - name: DB_CONNECTION_STRING
                        valueFrom:
                            secretKeyRef:
                                name: db-connection-string
                                key: DB_CONNECTION_STRING
